package cmd

import (
	"context"
	"fmt"
	"strconv"

	"github.com/spf13/cobra"
	"github.com/strscp/cli/internal/api"
	"github.com/strscp/cli/internal/output"
	"github.com/strscp/cli/pkg/models"
)

var topicsCmd = &cobra.Command{
	Use:     "topics",
	Aliases: []string{"t", "top"},
	Short:   "Manage review topics",
}

var (
	topicConnectionID int
	topicPerPage      int
	topicPage         int
	topicAll          bool
)

var topicsListCmd = &cobra.Command{
	Use:     "list",
	Aliases: []string{"ls"},
	Short:   "List topics",
	Example: `  starscope-cli topics list
  starscope-cli topics list --connection-id 5
  starscope-cli t ls --output csv`,
	RunE: func(cmd *cobra.Command, args []string) error {
		client, err := newAPIClient()
		if err != nil {
			return err
		}
		f, err := newFormatter()
		if err != nil {
			return err
		}

		params := api.ListTopicsParams{
			ConnectionID: topicConnectionID,
			PerPage:      topicPerPage,
			Page:         topicPage,
		}

		ctx := context.Background()

		if topicAll {
			topics, err := client.Topics.ListAll(ctx, params)
			if err != nil {
				return err
			}
			return formatTopicList(f, topics)
		}

		resp, err := client.Topics.List(ctx, params)
		if err != nil {
			return err
		}

		if err := formatTopicList(f, resp.Data); err != nil {
			return err
		}

		paginationFooter("topics", resp.Meta)
		return nil
	},
}

var topicsShowCmd = &cobra.Command{
	Use:     "show <id>",
	Aliases: []string{"s"},
	Short:   "Show a topic",
	Example: `  starscope-cli topics show 42`,
	Args:    cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		id, err := strconv.Atoi(args[0])
		if err != nil {
			return fmt.Errorf("invalid topic ID: %s", args[0])
		}

		client, err := newAPIClient()
		if err != nil {
			return err
		}
		f, err := newFormatter()
		if err != nil {
			return err
		}

		topic, err := client.Topics.Get(context.Background(), id)
		if err != nil {
			return err
		}

		return formatTopicDetail(f, topic)
	},
}

var topicsReviewsCmd = &cobra.Command{
	Use:   "reviews <topic-id>",
	Short: "List reviews for a topic",
	Example: `  starscope-cli topics reviews 42`,
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		id, err := strconv.Atoi(args[0])
		if err != nil {
			return fmt.Errorf("invalid topic ID: %s", args[0])
		}

		client, err := newAPIClient()
		if err != nil {
			return err
		}
		f, err := newFormatter()
		if err != nil {
			return err
		}

		resp, err := client.Topics.Reviews(context.Background(), id, topicPerPage, topicPage)
		if err != nil {
			return err
		}

		if err := formatReviewList(f, resp.Data); err != nil {
			return err
		}

		paginationFooter("reviews", resp.Meta)
		return nil
	},
}

func formatTopicList(f *output.Formatter, topics []models.Topic) error {
	headers := []string{"ID", "LABEL", "REVIEWS", "AVG RATING", "AVG SENTIMENT"}
	rows := make([][]string, len(topics))
	for i, t := range topics {
		avgRating := "-"
		if t.AvgRating != nil {
			avgRating = fmt.Sprintf("%.1f", *t.AvgRating)
		}
		avgSentiment := "-"
		if t.AvgSentiment != nil {
			avgSentiment = fmt.Sprintf("%.2f", *t.AvgSentiment)
		}
		rows[i] = []string{
			strconv.Itoa(t.ID),
			t.Label,
			strconv.Itoa(t.ReviewCount),
			avgRating,
			avgSentiment,
		}
	}
	return f.FormatList(headers, rows)
}

func formatTopicDetail(f *output.Formatter, t *models.Topic) error {
	avgRating := "-"
	if t.AvgRating != nil {
		avgRating = fmt.Sprintf("%.1f", *t.AvgRating)
	}
	avgSentiment := "-"
	if t.AvgSentiment != nil {
		avgSentiment = fmt.Sprintf("%.2f", *t.AvgSentiment)
	}

	fields := []output.Field{
		{Label: "ID", Value: strconv.Itoa(t.ID)},
		{Label: "Label", Value: t.Label},
		{Label: "Description", Value: deref(t.Description)},
		{Label: "Review Count", Value: strconv.Itoa(t.ReviewCount)},
		{Label: "Avg Rating", Value: avgRating},
		{Label: "Avg Sentiment", Value: avgSentiment},
		{Label: "Auto Generated", Value: fmt.Sprintf("%t", t.IsAutoGenerated)},
	}
	return f.FormatDetail(fields)
}

func init() {
	topicsListCmd.Flags().IntVar(&topicConnectionID, "connection-id", 0, "filter by connection ID")
	topicsListCmd.Flags().IntVar(&topicPerPage, "per-page", 20, "results per page (1-100)")
	topicsListCmd.Flags().IntVar(&topicPage, "page", 1, "page number")
	topicsListCmd.Flags().BoolVar(&topicAll, "all", false, "fetch all pages")

	topicsReviewsCmd.Flags().IntVar(&topicPerPage, "per-page", 15, "results per page (1-100)")
	topicsReviewsCmd.Flags().IntVar(&topicPage, "page", 1, "page number")

	topicsCmd.AddCommand(topicsListCmd)
	topicsCmd.AddCommand(topicsShowCmd)
	topicsCmd.AddCommand(topicsReviewsCmd)
	defaultToList(topicsCmd, topicsListCmd)
}
