package models

// Topic represents a review topic from the Starscope API.
type Topic struct {
	ID              int      `json:"id"`
	Label           string   `json:"label"`
	Description     *string  `json:"description"`
	ReviewCount     int      `json:"review_count"`
	AvgSentiment    *float64 `json:"avg_sentiment"`
	AvgRating       *float64 `json:"avg_rating"`
	IsAutoGenerated bool     `json:"is_auto_generated"`
	ConsolidatedAt  *string  `json:"consolidated_at"`
}
